name: chat_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  chat_bubbles: ^1.6.0
  fllama:
    git:
      url: https://github.com/Telosnex/fllama.git
      ref: main
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_easyloading: ^3.0.5
  flutter_markdown: ^0.7.4+1
  fluttertoast: ^8.2.8
  markdown: ^7.2.2
  path_provider: ^2.1.4
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
